# Generated by Django 6.1.1 on 2026-10-05 03:39

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_attempt', models.CharField(blank=True, max_length=150)),
                ('event_type', models.CharField(choices=[('login', 'เข้าสู่ระบบ'), ('logout', 'ออกจากระบบ'), ('failed', 'เข้าสู่ระบบล้มเหลว'), ('locked', 'ถูกล็อคบัญชี'), ('timeout', 'Session หมดอายุ')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'บันทึกเหตุการณ์การเข้าสู่ระบบ',
                'verbose_name_plural': 'บันทึกเหตุการณ์ทั้งหมด',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='ชื่อ')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='นามสกุล')),
                ('phone', models.CharField(blank=True, help_text='เช่น 0812345678', max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('avatar', models.ImageField(blank=True, help_text='PNG, JPG ≤ 5MB', null=True, upload_to=accounts.models.profile_avatar_path, verbose_name='รูปประจำตัว')),
                ('bio', models.TextField(blank=True, max_length=300, verbose_name='แนะนำตัวสั้นๆ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
            options={
                'verbose_name': 'โปรไฟล์ผู้ใช้',
                'verbose_name_plural': 'โปรไฟล์ผู้ใช้ทั้งหมด',
            },
        ),
    ]
