# Generated by Django 6.1.1 on 2026-10-05 03:57

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_idle_timeout_minutes', models.PositiveIntegerField(default=60, help_text='ระบบจะบังคับให้ออกจากระบบอัตโนมัติเมื่อผู้ใช้ไม่มีการใช้งานตามเวลาที่กำหนด (ค่าเริ่มต้น 60 นาที)', verbose_name='ระยะเวลาเซสชันหมดอายุเมื่อไม่ใช้งาน (นาที)')),
                ('max_login_attempts', models.PositiveIntegerField(default=5, help_text='เกณฑ์สำหรับป้องกันการโจมตีแบบ Brute-force (เช่น 5 ครั้ง)', verbose_name='จำนวนครั้งล็อกอินผิดพลาดสูงสุดก่อนระงับ (ครั้ง)')),
                ('enable_security_audit_log', models.BooleanField(default=True, help_text='บันทึก IP, User-Agent, เวลา เมื่อมีกิจกรรมเข้า-ออกจากระบบ', verbose_name='เปิดใช้งานระบบ Audit Log บันทึกเหตุการณ์ความปลอดภัย')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุดเมื่อ')),
            ],
            options={
                'verbose_name': 'การตั้งค่าระบบและความปลอดภัย',
                'verbose_name_plural': 'การตั้งค่าระบบและความปลอดภัย',
            },
        ),
        migrations.AlterModelOptions(
            name='loginevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'บันทึกเหตุการณ์ความปลอดภัย', 'verbose_name_plural': 'บันทึกเหตุการณ์ความปลอดภัยทั้งหมด'},
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='event_type',
            field=models.CharField(choices=[('login', 'เข้าสู่ระบบสำเร็จ'), ('logout', 'ออกจากระบบ'), ('failed', 'เข้าสู่ระบบล้มเหลว'), ('locked', 'ถูกล็อคบัญชีชั่วคราว'), ('timeout', 'เซสชันหมดอายุ (Idle Timeout)'), ('password_change', 'เปลี่ยนรหัสผ่านสำเร็จ')], max_length=30, verbose_name='ประเภทเหตุการณ์'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='เวลาที่บันทึก'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='username_attempt',
            field=models.CharField(blank=True, max_length=150, verbose_name='ชื่อผู้ใช้ที่ระบุ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='รองรับไฟล์ PNG, JPG, WEBP (ขนาดไม่เกิน 5MB)', null=True, upload_to=accounts.models.profile_avatar_path, verbose_name='รูปประจำตัว'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='คำแนะนำตัวสั้นๆ (Bio)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด'),
        ),
    ]
